import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateIdentityKeyPair, signPayload, verifySignature } from './identity.js';

/**
 * Cross-runtime interop.
 *
 * PC identity is verified by Node but produced by the .NET agent, so the two runtimes have
 * to agree on the curve, the hash, the signature encoding (DER, not IEEE P1363), and the
 * base64url encoding of both key and signature. A golden vector generated by .NET is
 * checked in so a change to any of those on either side fails here instead of silently
 * locking every enrolled PC out of the cloud.
 *
 * The matching vector for the other direction lives in the agent's own test suite.
 */
const testdata = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../testdata');

interface SignatureVector {
  readonly publicKey: string;
  readonly payload: string;
  readonly signature: string;
}

test('a signature produced by the .NET agent verifies in the cloud', () => {
  const vector = JSON.parse(
    readFileSync(path.join(testdata, 'dotnet-signature.json'), 'utf8'),
  ) as SignatureVector;

  assert.equal(verifySignature(vector.publicKey, vector.payload, vector.signature), true);
});

test('the .NET vector is rejected for a different payload', () => {
  const vector = JSON.parse(
    readFileSync(path.join(testdata, 'dotnet-signature.json'), 'utf8'),
  ) as SignatureVector;

  // The signed payload binds the PC id and the nonce, so changing either must invalidate it.
  assert.equal(
    verifySignature(vector.publicKey, vector.payload.replace('NONCE-ABC123', 'NONCE-XYZ789'), vector.signature),
    false,
  );
  assert.equal(
    verifySignature(
      vector.publicKey,
      vector.payload.replace('01J9ZQK7T0000000000000000A', '01J9ZQK7T0000000000000000B'),
      vector.signature,
    ),
    false,
  );
});

test('the .NET vector uses the encodings the cloud expects', () => {
  const vector = JSON.parse(
    readFileSync(path.join(testdata, 'dotnet-signature.json'), 'utf8'),
  ) as SignatureVector;

  assert.match(vector.publicKey, /^[A-Za-z0-9_-]+$/, 'public key must be base64url');
  assert.match(vector.signature, /^[A-Za-z0-9_-]+$/, 'signature must be base64url');

  // SPKI DER for a P-256 public key is 91 bytes; a different curve would not match.
  assert.equal(Buffer.from(vector.publicKey, 'base64url').length, 91);
  // DER sequences start with 0x30; an IEEE P1363 (r||s) signature would not.
  assert.equal(Buffer.from(vector.signature, 'base64url')[0], 0x30);
});

test('a Node-generated signature uses the same encodings', () => {
  const keys = generateIdentityKeyPair();
  const signature = signPayload(keys.privateKey, 'wolf-agent-auth v1 PC NONCE');

  assert.equal(Buffer.from(keys.publicKey, 'base64url').length, 91);
  assert.equal(Buffer.from(signature, 'base64url')[0], 0x30);
  assert.equal(verifySignature(keys.publicKey, 'wolf-agent-auth v1 PC NONCE', signature), true);
});
