import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { challengeSigningPayload } from '@wolf/protocol';
import { generateIdentityKeyPair, signPayload, verifySignature } from './identity.js';

/**
 * Cross-runtime interop.
 *
 * PC identity is verified by Node but produced by the .NET agent, so the two runtimes have
 * to agree on the curve, the hash, the signature encoding (DER, not IEEE P1363), and the
 * base64url encoding of both key and signature. A golden vector generated by .NET is
 * checked in so a change to any of those on either side fails here instead of silently
 * locking every enrolled PC out of the cloud.
 *
 * The matching vector for the other direction lives in the agent's own test suite.
 */
const testdata = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../testdata');

interface SignatureVector {
  readonly pcId: string;
  readonly nonce: string;
  /** UTF-8 bytes of the canonical payload, hex encoded so the NUL separators survive. */
  readonly payloadHex: string;
  readonly publicKey: string;
  readonly signature: string;
}

function loadVector(): SignatureVector {
  return JSON.parse(
    readFileSync(path.join(testdata, 'dotnet-signature.json'), 'utf8'),
  ) as SignatureVector;
}

/** What .NET actually signed, reconstructed from the vector rather than retyped. */
function signedPayload(vector: SignatureVector): string {
  return Buffer.from(vector.payloadHex, 'hex').toString('utf8');
}

/**
 * The test that was missing, and the reason a whole release could not connect.
 *
 * Everything else here checks the *cryptography* — curve, hash, DER, base64url — against a
 * payload string carried inside the vector, which both sides were happy to sign whatever it
 * said. Meanwhile the two runtimes built that string differently: the cloud separated the
 * fields with NUL and the agent with spaces. Enrolment succeeded, every handshake after it
 * was refused with `bad-signature`, and no test noticed because no test ever compared the
 * two functions.
 */
test('the cloud and the .NET agent build the same signing payload', () => {
  const vector = loadVector();

  assert.equal(
    challengeSigningPayload(vector.pcId, vector.nonce),
    signedPayload(vector),
    'the cloud must build exactly the bytes the agent signed',
  );
});

test('a signature produced by the .NET agent verifies in the cloud', () => {
  const vector = loadVector();

  // Verified against the payload the *cloud* builds, not the one recorded in the vector:
  // that is the string the relay will actually check against in production.
  assert.equal(
    verifySignature(
      vector.publicKey,
      challengeSigningPayload(vector.pcId, vector.nonce),
      vector.signature,
    ),
    true,
  );
});

test('the .NET vector is rejected for a different payload', () => {
  const vector = loadVector();

  // The signed payload binds the PC id and the nonce, so changing either must invalidate it.
  assert.equal(
    verifySignature(
      vector.publicKey,
      challengeSigningPayload(vector.pcId, 'NONCE-XYZ789'),
      vector.signature,
    ),
    false,
  );
  assert.equal(
    verifySignature(
      vector.publicKey,
      challengeSigningPayload('01J9ZQK7T0000000000000000B', vector.nonce),
      vector.signature,
    ),
    false,
  );
});

test('the .NET vector uses the encodings the cloud expects', () => {
  const vector = loadVector();

  assert.match(vector.publicKey, /^[A-Za-z0-9_-]+$/, 'public key must be base64url');
  assert.match(vector.signature, /^[A-Za-z0-9_-]+$/, 'signature must be base64url');

  // SPKI DER for a P-256 public key is 91 bytes; a different curve would not match.
  assert.equal(Buffer.from(vector.publicKey, 'base64url').length, 91);
  // DER sequences start with 0x30; an IEEE P1363 (r||s) signature would not.
  assert.equal(Buffer.from(vector.signature, 'base64url')[0], 0x30);
});

test('a Node-generated signature uses the same encodings', () => {
  const keys = generateIdentityKeyPair();
  const signature = signPayload(keys.privateKey, 'wolf-agent-auth v1 PC NONCE');

  assert.equal(Buffer.from(keys.publicKey, 'base64url').length, 91);
  assert.equal(Buffer.from(signature, 'base64url')[0], 0x30);
  assert.equal(verifySignature(keys.publicKey, 'wolf-agent-auth v1 PC NONCE', signature), true);
});
