using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Wolf.Agent.Core.Identity;
using Wolf.Agent.Core.Protocol;
using Xunit;

namespace Wolf.Agent.Core.Tests;

/// <summary>
/// Cross-runtime interop for PC identity.
///
/// The cloud signs nothing here, but it does verify what this agent signs, so both sides
/// must agree on P-256, SHA-256, DER signatures, and base64url encoding. A golden vector
/// generated by the cloud's own crypto is checked in: if either side changes its encoding,
/// this test fails rather than every enrolled PC quietly losing its ability to connect.
/// </summary>
public sealed class IdentityInteropTests
{
    private sealed record SignatureVector(string PublicKey, string Payload, string Signature);

    private static SignatureVector LoadVector()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "testdata", "node-signature.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(path));
        JsonElement root = document.RootElement;

        return new SignatureVector(
            root.GetProperty("publicKey").GetString()!,
            root.GetProperty("payload").GetString()!,
            root.GetProperty("signature").GetString()!);
    }

    [Fact]
    public void A_signature_produced_by_the_cloud_verifies_in_the_agent()
    {
        SignatureVector vector = LoadVector();

        using ECDsa key = ECDsa.Create();
        key.ImportSubjectPublicKeyInfo(Base64Url.Decode(vector.PublicKey), out _);

        Assert.True(key.VerifyData(
            Encoding.UTF8.GetBytes(vector.Payload),
            Base64Url.Decode(vector.Signature),
            HashAlgorithmName.SHA256,
            DSASignatureFormat.Rfc3279DerSequence));
    }

    [Fact]
    public void A_signature_does_not_verify_for_a_different_payload()
    {
        SignatureVector vector = LoadVector();

        using ECDsa key = ECDsa.Create();
        key.ImportSubjectPublicKeyInfo(Base64Url.Decode(vector.PublicKey), out _);

        Assert.False(key.VerifyData(
            Encoding.UTF8.GetBytes(vector.Payload.Replace("NONCE-NODE-42", "NONCE-NODE-43", StringComparison.Ordinal)),
            Base64Url.Decode(vector.Signature),
            HashAlgorithmName.SHA256,
            DSASignatureFormat.Rfc3279DerSequence));
    }

    [Fact]
    public void An_agent_signature_uses_the_encodings_the_cloud_expects()
    {
        (ECDsa key, string publicKey) = PcIdentityStore.CreateKeyPair();
        using (key)
        {
            byte[] signature = key.SignData(
                Encoding.UTF8.GetBytes("wolf-agent-auth v1 PC NONCE"),
                HashAlgorithmName.SHA256,
                DSASignatureFormat.Rfc3279DerSequence);

            // SPKI DER for P-256 is 91 bytes; a different curve would not match.
            Assert.Equal(91, Base64Url.Decode(publicKey).Length);
            // DER sequences start with 0x30; an IEEE P1363 signature would not.
            Assert.Equal(0x30, signature[0]);
            Assert.Matches("^[A-Za-z0-9_-]+$", publicKey);
            Assert.Matches("^[A-Za-z0-9_-]+$", Base64Url.Encode(signature));
        }
    }

    [Fact]
    public void The_signing_payload_binds_the_pc_and_the_nonce()
    {
        // Both sides build this string independently; if they ever disagree, no PC connects.
        Assert.Equal(
            "wolf-agent-auth v1 PC-1 NONCE-1",
            WolfProtocol.ChallengeSigningPayload("PC-1", "NONCE-1"));
    }

    [Theory]
    [InlineData("")]
    [InlineData("A")]
    [InlineData("AAAAA")]
    public void Base64Url_round_trips_every_length_class(string _)
    {
        for (int length = 0; length < 40; length++)
        {
            byte[] bytes = RandomNumberGenerator.GetBytes(length);
            Assert.Equal(bytes, Base64Url.Decode(Base64Url.Encode(bytes)));
        }
    }
}
