using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Wolf.Agent.Core.Identity;
using Wolf.Agent.Core.Protocol;
using Xunit;

namespace Wolf.Agent.Core.Tests;

/// <summary>
/// Cross-runtime interop for PC identity.
///
/// The cloud signs nothing here, but it does verify what this agent signs, so both sides
/// must agree on P-256, SHA-256, DER signatures, and base64url encoding. A golden vector
/// generated by the cloud's own crypto is checked in: if either side changes its encoding,
/// this test fails rather than every enrolled PC quietly losing its ability to connect.
/// </summary>
public sealed class IdentityInteropTests
{
    private sealed record SignatureVector(
        string PcId,
        string Nonce,
        /// <summary>UTF-8 bytes of the payload, hex encoded so the NUL separators survive.</summary>
        string PayloadHex,
        string PublicKey,
        string Signature)
    {
        /// <summary>The bytes the cloud actually signed.</summary>
        public string Payload => Encoding.UTF8.GetString(Convert.FromHexString(PayloadHex));
    }

    private static SignatureVector LoadVector()
    {
        string path = Path.Combine(AppContext.BaseDirectory, "testdata", "node-signature.json");
        using JsonDocument document = JsonDocument.Parse(File.ReadAllText(path));
        JsonElement root = document.RootElement;

        return new SignatureVector(
            root.GetProperty("pcId").GetString()!,
            root.GetProperty("nonce").GetString()!,
            root.GetProperty("payloadHex").GetString()!,
            root.GetProperty("publicKey").GetString()!,
            root.GetProperty("signature").GetString()!);
    }

    [Fact]
    public void A_signature_produced_by_the_cloud_verifies_in_the_agent()
    {
        SignatureVector vector = LoadVector();

        using ECDsa key = ECDsa.Create();
        key.ImportSubjectPublicKeyInfo(Base64Url.Decode(vector.PublicKey), out _);

        Assert.True(key.VerifyData(
            Encoding.UTF8.GetBytes(vector.Payload),
            Base64Url.Decode(vector.Signature),
            HashAlgorithmName.SHA256,
            DSASignatureFormat.Rfc3279DerSequence));
    }

    [Fact]
    public void A_signature_does_not_verify_for_a_different_payload()
    {
        SignatureVector vector = LoadVector();

        using ECDsa key = ECDsa.Create();
        key.ImportSubjectPublicKeyInfo(Base64Url.Decode(vector.PublicKey), out _);

        Assert.False(key.VerifyData(
            Encoding.UTF8.GetBytes(WolfProtocol.ChallengeSigningPayload(vector.PcId, "NONCE-NODE-43")),
            Base64Url.Decode(vector.Signature),
            HashAlgorithmName.SHA256,
            DSASignatureFormat.Rfc3279DerSequence));
    }

    [Fact]
    public void An_agent_signature_uses_the_encodings_the_cloud_expects()
    {
        (ECDsa key, string publicKey) = PcIdentityStore.CreateKeyPair();
        using (key)
        {
            byte[] signature = key.SignData(
                Encoding.UTF8.GetBytes(WolfProtocol.ChallengeSigningPayload("PC", "NONCE")),
                HashAlgorithmName.SHA256,
                DSASignatureFormat.Rfc3279DerSequence);

            // SPKI DER for P-256 is 91 bytes; a different curve would not match.
            Assert.Equal(91, Base64Url.Decode(publicKey).Length);
            // DER sequences start with 0x30; an IEEE P1363 signature would not.
            Assert.Equal(0x30, signature[0]);
            Assert.Matches("^[A-Za-z0-9_-]+$", publicKey);
            Assert.Matches("^[A-Za-z0-9_-]+$", Base64Url.Encode(signature));
        }
    }

    [Fact]
    public void The_signing_payload_binds_the_pc_and_the_nonce()
    {
        // NUL between the fields, not a space. The separator has to be something that
        // cannot occur inside a field, or two different (pcId, nonce) pairs could produce
        // the same bytes and one PC's signature would authenticate another.
        Assert.Equal(
            "wolf-agent-auth\0v1\0PC-1\0NONCE-1",
            WolfProtocol.ChallengeSigningPayload("PC-1", "NONCE-1"));
    }

    /// <summary>
    /// The agent builds the same bytes the cloud signed.
    ///
    /// This is the test that was missing, and its absence cost a build in which every PC
    /// enrolled successfully and then failed every handshake with "bad-signature": the
    /// cloud separated the payload's fields with NUL and the agent with spaces, while each
    /// suite checked only its own crypto against a payload string carried inside the shared
    /// vector — which both were happy to sign whatever it said. The vectors now record the
    /// bytes, and each side rebuilds the string with its own function and compares.
    /// </summary>
    [Fact]
    public void The_shared_vector_records_the_bytes_this_agent_would_sign()
    {
        SignatureVector vector = LoadVector();

        Assert.Equal(
            WolfProtocol.ChallengeSigningPayload(vector.PcId, vector.Nonce),
            vector.Payload);
    }

    [Theory]
    [InlineData("")]
    [InlineData("A")]
    [InlineData("AAAAA")]
    public void Base64Url_round_trips_every_length_class(string _)
    {
        for (int length = 0; length < 40; length++)
        {
            byte[] bytes = RandomNumberGenerator.GetBytes(length);
            Assert.Equal(bytes, Base64Url.Decode(Base64Url.Encode(bytes)));
        }
    }
}
