-- WOLF core schema.
--
-- Conventions:
--   * Identifiers are ULID-style CHAR(26) strings generated by the application, not the
--     database, so an id can be created before the row is written and logged alongside it.
--   * Timestamps are TIMESTAMPTZ and always stored in UTC.
--   * Anything that can be revoked has an explicit revoked_at rather than being deleted,
--     so audit trails keep resolving.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version      TEXT PRIMARY KEY,
    applied_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    checksum     TEXT NOT NULL
);

-- ---------------------------------------------------------------------------
-- Account
-- ---------------------------------------------------------------------------

-- WOLF is a single-owner product. There is no public registration path; the first and
-- only account is created by the bootstrap script, and this constraint makes a second
-- account impossible even if an endpoint were ever added by mistake.
CREATE TABLE IF NOT EXISTS users (
    id                CHAR(26) PRIMARY KEY,
    email             TEXT NOT NULL UNIQUE,
    password_hash     TEXT NOT NULL,
    display_name      TEXT NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    password_changed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Sliding brute-force state; see @wolf/auth lockout policy.
    failed_login_count INTEGER NOT NULL DEFAULT 0,
    last_failed_login_at TIMESTAMPTZ,
    last_login_at     TIMESTAMPTZ,
    is_owner          BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS users_single_owner ON users ((is_owner)) WHERE is_owner;

-- ---------------------------------------------------------------------------
-- Client devices
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_devices (
    id             CHAR(26) PRIMARY KEY,
    user_id        CHAR(26) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind           TEXT NOT NULL CHECK (kind IN ('web', 'pwa', 'android', 'windows-control-panel')),
    name           TEXT NOT NULL,
    status         TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('pending', 'active', 'revoked')),
    -- Ed25519 SPKI, base64url. The private key never leaves the device.
    public_key     TEXT,
    platform       TEXT,
    lan_authorized BOOLEAN NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at   TIMESTAMPTZ,
    revoked_at     TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS user_devices_user_idx ON user_devices (user_id, status);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    token_id     TEXT PRIMARY KEY,
    family_id    TEXT NOT NULL,
    user_id      CHAR(26) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id    CHAR(26) NOT NULL REFERENCES user_devices(id) ON DELETE CASCADE,
    -- SHA-256 of the token secret. The secret itself is never stored.
    secret_hash  TEXT NOT NULL,
    issued_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at   TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS refresh_tokens_family_idx ON refresh_tokens (family_id);
CREATE INDEX IF NOT EXISTS refresh_tokens_device_idx ON refresh_tokens (device_id);
CREATE INDEX IF NOT EXISTS refresh_tokens_expiry_idx ON refresh_tokens (expires_at)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

-- ---------------------------------------------------------------------------
-- PCs
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pcs (
    id                  CHAR(26) PRIMARY KEY,
    user_id             CHAR(26) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name                TEXT NOT NULL,
    hostname            TEXT,
    registration_state  TEXT NOT NULL DEFAULT 'pending'
                        CHECK (registration_state IN ('pending', 'active', 'revoked')),
    status              TEXT NOT NULL DEFAULT 'offline'
                        CHECK (status IN ('online', 'offline', 'unreachable', 'sleeping')),
    agent_version       TEXT,
    -- Ed25519 SPKI, base64url. Set during enrollment; rotating it re-enrolls the PC.
    public_key          TEXT,
    windows_session_state TEXT NOT NULL DEFAULT 'unknown'
                        CHECK (windows_session_state IN
                               ('desktop', 'locked', 'login', 'restarting', 'offline', 'unknown')),
    connection_route    TEXT CHECK (connection_route IN ('lan', 'p2p', 'relay')),
    -- Kill switch. Remote callers may only ever set this to FALSE; clearing it requires
    -- local authentication on the PC itself.
    remote_access_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    local_kill_switch_engaged BOOLEAN NOT NULL DEFAULT FALSE,
    favorite            BOOLEAN NOT NULL DEFAULT FALSE,
    tags                TEXT[] NOT NULL DEFAULT '{}',
    -- Wake-on-LAN target. Stored so a peer agent can wake this PC; never returned in full
    -- to clients that do not need it.
    wake_mac_address    TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at        TIMESTAMPTZ,
    revoked_at          TIMESTAMPTZ,
    UNIQUE (user_id, name)
);

CREATE INDEX IF NOT EXISTS pcs_user_idx ON pcs (user_id, registration_state);

-- Single-use enrollment tokens. The installer exchanges one for a PC identity; it is
-- hashed at rest so a leaked database cannot be used to enrol a rogue machine.
CREATE TABLE IF NOT EXISTS pc_enrollment_tokens (
    id          CHAR(26) PRIMARY KEY,
    user_id     CHAR(26) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,
    label       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    consumed_by_pc CHAR(26) REFERENCES pcs(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS pc_enrollment_tokens_user_idx ON pc_enrollment_tokens (user_id)
    WHERE consumed_at IS NULL;

CREATE TABLE IF NOT EXISTS pc_capabilities (
    pc_id                          CHAR(26) PRIMARY KEY REFERENCES pcs(id) ON DELETE CASCADE,
    hardware_video_encoders        TEXT[] NOT NULL DEFAULT '{}',
    preferred_video_codec          TEXT,
    display_count                  INTEGER NOT NULL DEFAULT 0,
    audio_capture_available        BOOLEAN NOT NULL DEFAULT FALSE,
    wake_on_lan_capable            BOOLEAN NOT NULL DEFAULT FALSE,
    privileged_helper_available    BOOLEAN NOT NULL DEFAULT FALSE,
    secure_desktop_capture_available BOOLEAN NOT NULL DEFAULT FALSE,
    remote_unlock_provisioned      BOOLEAN NOT NULL DEFAULT FALSE,
    gpu_vendors                    TEXT[] NOT NULL DEFAULT '{}',
    windows_build                  TEXT,
    -- Command types this agent build can execute. The API refuses to dispatch anything
    -- absent from this list instead of queueing a command that can never run.
    supported_commands             TEXT[] NOT NULL DEFAULT '{}',
    updated_at                     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pc_hardware (
    pc_id              CHAR(26) PRIMARY KEY REFERENCES pcs(id) ON DELETE CASCADE,
    cpu_model          TEXT,
    cpu_cores          INTEGER,
    cpu_threads        INTEGER,
    total_memory_bytes BIGINT,
    gpus               TEXT[] NOT NULL DEFAULT '{}',
    os_name            TEXT,
    os_version         TEXT,
    os_build           TEXT,
    architecture       TEXT,
    booted_at          TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pc_health (
    pc_id        CHAR(26) PRIMARY KEY REFERENCES pcs(id) ON DELETE CASCADE,
    score        INTEGER CHECK (score BETWEEN 0 AND 100),
    factors      JSONB NOT NULL DEFAULT '[]'::jsonb,
    evaluated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS pc_groups (
    id         CHAR(26) PRIMARY KEY,
    user_id    CHAR(26) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name       TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS pc_group_members (
    group_id CHAR(26) NOT NULL REFERENCES pc_groups(id) ON DELETE CASCADE,
    pc_id    CHAR(26) NOT NULL REFERENCES pcs(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, pc_id)
);

-- ---------------------------------------------------------------------------
-- Sessions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sessions (
    id             CHAR(26) PRIMARY KEY,
    user_id        CHAR(26) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id      CHAR(26) NOT NULL REFERENCES user_devices(id) ON DELETE CASCADE,
    pc_id          CHAR(26) NOT NULL REFERENCES pcs(id) ON DELETE CASCADE,
    mode           TEXT NOT NULL DEFAULT 'control' CHECK (mode IN ('view-only', 'control')),
    status         TEXT NOT NULL DEFAULT 'active'
                   CHECK (status IN ('pending', 'active', 'idle', 'ended', 'expired')),
    state          TEXT NOT NULL DEFAULT 'CONNECTING',
    route          TEXT CHECK (route IN ('lan', 'p2p', 'relay')),
    -- Capabilities granted at creation. Never widened in place; a new grant is a new row
    -- in session_events plus an explicit update, so the audit trail shows the change.
    capabilities   TEXT[] NOT NULL DEFAULT '{}',
    started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at     TIMESTAMPTZ NOT NULL,
    ended_at       TIMESTAMPTZ,
    end_reason     TEXT
);

CREATE INDEX IF NOT EXISTS sessions_pc_active_idx ON sessions (pc_id) WHERE ended_at IS NULL;
CREATE INDEX IF NOT EXISTS sessions_device_idx ON sessions (device_id, started_at DESC);

-- Exclusive resources (input, terminal, file operations, power, configuration) are
-- arbitrated independently, so one session holding the terminal does not block another
-- session's file transfer.
CREATE TABLE IF NOT EXISTS session_resource_leases (
    pc_id       CHAR(26) NOT NULL REFERENCES pcs(id) ON DELETE CASCADE,
    resource    TEXT NOT NULL CHECK (resource IN
                ('input', 'terminal', 'file-operations', 'power', 'configuration')),
    session_id  CHAR(26) NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    acquired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (pc_id, resource)
);

CREATE TABLE IF NOT EXISTS session_events (
    id         CHAR(26) PRIMARY KEY,
    session_id CHAR(26) NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    type       TEXT NOT NULL,
    detail     JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS session_events_session_idx ON session_events (session_id, at DESC);

-- ---------------------------------------------------------------------------
-- Commands
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS commands (
    id             CHAR(26) PRIMARY KEY,
    pc_id          CHAR(26) NOT NULL REFERENCES pcs(id) ON DELETE CASCADE,
    session_id     CHAR(26) REFERENCES sessions(id) ON DELETE SET NULL,
    user_id        CHAR(26) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    device_id      CHAR(26) NOT NULL REFERENCES user_devices(id) ON DELETE CASCADE,
    request_id     CHAR(26) NOT NULL,
    type           TEXT NOT NULL,
    risk_level     TEXT NOT NULL CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    status         TEXT NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'queued', 'sent', 'running', 'completed',
                                     'failed', 'cancelled', 'expired', 'rejected')),
    -- Validated command payload. Never contains credentials: privileged material is
    -- referenced by id and resolved on the PC.
    payload        JSONB NOT NULL,
    authorization_context JSONB NOT NULL,
    idempotency_key TEXT NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- A command that has not reached the agent by this instant is expired, never run late.
    expires_at     TIMESTAMPTZ NOT NULL,
    sent_at        TIMESTAMPTZ,
    started_at     TIMESTAMPTZ,
    completed_at   TIMESTAMPTZ,
    error_code     TEXT,
    error_message  TEXT,
    -- TRUE when the failure is a Windows platform limitation rather than a WOLF fault.
    error_is_limitation BOOLEAN NOT NULL DEFAULT FALSE,
    result         JSONB
);

-- A repeated idempotency key for the same PC resolves to the original command rather than
-- running the action twice.
CREATE UNIQUE INDEX IF NOT EXISTS commands_idempotency_idx
    ON commands (pc_id, idempotency_key);
CREATE INDEX IF NOT EXISTS commands_pc_pending_idx ON commands (pc_id, created_at)
    WHERE status IN ('pending', 'queued', 'sent', 'running');
CREATE INDEX IF NOT EXISTS commands_pc_recent_idx ON commands (pc_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- Telemetry
-- ---------------------------------------------------------------------------

-- Raw samples are partitioned by day: retention is a DROP of old partitions rather than a
-- DELETE over hundreds of millions of rows.
CREATE TABLE IF NOT EXISTS telemetry_samples (
    pc_id       CHAR(26) NOT NULL,
    sampled_at  TIMESTAMPTZ NOT NULL,
    -- The full validated sample. Column extraction happens in the aggregation job.
    sample      JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (pc_id, sampled_at)
) PARTITION BY RANGE (sampled_at);

CREATE TABLE IF NOT EXISTS telemetry_aggregates (
    pc_id        CHAR(26) NOT NULL REFERENCES pcs(id) ON DELETE CASCADE,
    resolution   TEXT NOT NULL CHECK (resolution IN ('5m', '1h', '1d')),
    metric       TEXT NOT NULL,
    series_key   TEXT NOT NULL DEFAULT '',
    bucket_start TIMESTAMPTZ NOT NULL,
    min_value    DOUBLE PRECISION,
    max_value    DOUBLE PRECISION,
    avg_value    DOUBLE PRECISION,
    p95_value    DOUBLE PRECISION,
    sample_count INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (pc_id, resolution, metric, series_key, bucket_start)
);

CREATE INDEX IF NOT EXISTS telemetry_aggregates_lookup_idx
    ON telemetry_aggregates (pc_id, metric, resolution, bucket_start DESC);

-- ---------------------------------------------------------------------------
-- Audit and security
-- ---------------------------------------------------------------------------

-- Audit rows are append-only and are never rolled up. They must never contain secrets,
-- clipboard contents, file contents, or terminal output.
CREATE TABLE IF NOT EXISTS audit_logs (
    id           CHAR(26) PRIMARY KEY,
    occurred_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    category     TEXT NOT NULL,
    action       TEXT NOT NULL,
    outcome      TEXT NOT NULL CHECK (outcome IN ('success', 'failure', 'denied', 'pending')),
    risk_level   TEXT NOT NULL CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
    user_id      CHAR(26) REFERENCES users(id) ON DELETE SET NULL,
    device_id    CHAR(26) REFERENCES user_devices(id) ON DELETE SET NULL,
    pc_id        CHAR(26) REFERENCES pcs(id) ON DELETE SET NULL,
    session_id   CHAR(26) REFERENCES sessions(id) ON DELETE SET NULL,
    request_id   CHAR(26),
    source_ip    INET,
    route        TEXT CHECK (route IN ('lan', 'p2p', 'relay')),
    target       JSONB,
    before_value JSONB,
    after_value  JSONB,
    error_code   TEXT,
    reference_id TEXT
);

CREATE INDEX IF NOT EXISTS audit_logs_time_idx ON audit_logs (occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_pc_idx ON audit_logs (pc_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS audit_logs_category_idx ON audit_logs (category, occurred_at DESC);

CREATE TABLE IF NOT EXISTS security_events (
    id          CHAR(26) PRIMARY KEY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    type        TEXT NOT NULL,
    user_id     CHAR(26) REFERENCES users(id) ON DELETE SET NULL,
    device_id   CHAR(26) REFERENCES user_devices(id) ON DELETE SET NULL,
    pc_id       CHAR(26) REFERENCES pcs(id) ON DELETE SET NULL,
    source_ip   INET,
    detail      JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS security_events_time_idx ON security_events (occurred_at DESC);

-- System events reported by an agent that were not the result of a command.
CREATE TABLE IF NOT EXISTS system_events (
    id       CHAR(26) PRIMARY KEY,
    pc_id    CHAR(26) NOT NULL REFERENCES pcs(id) ON DELETE CASCADE,
    at       TIMESTAMPTZ NOT NULL,
    type     TEXT NOT NULL,
    detail   JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS system_events_pc_idx ON system_events (pc_id, at DESC);
